language: java

addons:
  sonarcloud:
    organization: "newtonjose-github" # the key of the org you chose at step #3
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - cd aula-01/java
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=newtonjose_cs-2019-01 -Dsonar.organization=newtonjose-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jdk:
  - openjdk9
